name: dbt CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake  # or dbt-bigquery/dbt-postgres depending on your adapter

      - name: Install dbt packages
        run: dbt deps

      - name: Compile project
        run: dbt compile --target ci

      - name: Run dbt tests
        run: dbt test --target ci

      - name: Run dbt models (excluding long running)
        run: dbt run --target ci --exclude tag:long_running
