name: 'sequra_analytics'
version: '1.0.0'
config-version: 2

profile: 'sequra_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  sequra_analytics:
    staging:
      materialized: view
      schema: staging
    intermediate:
      materialized: view
      schema: intermediate
    marts:
      materialized: table
      schema: marts

seeds:
  sequra_analytics:
    schema: raw_data
    orders_merchant:
      column_types:
        order_id: integer
        shopper_id: integer
        merchant_id: integer
        order_date: varchar
      merchants:
        column_types:
         merchant_id: integer
         merchant_name: varchar
    orders_financial:
      column_types:
        order_id: integer
        shopper_id: integer
        order_date: date
        product_id: integer
        merchant_id: integer
        is_in_default: boolean
        days_unbalanced: integer
        current_order_value: decimal(10,2)
        overdue_principal: decimal(10,2)
        overdue_fees: decimal(10,2)
    dim_shoppers:
      column_types:
        shopper_id: integer
        age: integer