
version: 2

models:
    - name: orders_merchant_STG
      description: "Staging orders by merchant_id"
      columns:
          - name: order_id
          - name: shopper_id
          - name: merchant_id
          - name: order_date

    - name: merchant_name_STG
      description: "Staging merchant name"
      columns:
          - name: merchant_id
          - name: merchant_name

    - name: reccurence_rate_by_merchant_calculation
      description: "Final output"
      columns:
          - name: merchant_name
          - name: month
          - name: reccurence_rate